default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('POSTGRES_USER', 'todo_list') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'todo_list') %>

development:
  <<: *default
  database: todo_list_development

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB', 'todo_list_test') %>

production:
  <<: *default
  database: todo_list_production
